apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-api
  template:
    metadata:
      labels:
        app: restaurant-api
    spec:
      containers:
        - name: restaurant-api
          image: DOCKER_HUP/restaurant-api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-api-service
spec:
  type: LoadBalancer
  selector:
    app: restaurant-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000