apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  RESTAURANT_APP_PORT: 3000
  RESTAURANT_SERVICE_PORT: 4000
  MONGO_DB_URL: mongodb://mongo-db:27017/restaurant?replicaSet=rs0&directConnection=true
  RABBITMQ: amqp://admin:admin@rabbitmq:5672
  ELASTIC_CONNECTION: http://elasticsearch:9200
  ELASTIC_USER: elastic
  ELASTIC_PASSWORD: password
  MESSAGE_QUEUE: orders_queue
  REDISHOST: redis
  REDISPORT: 6397